### PR TITLE
Scrolling

### PR DESCRIPTION
**Pull request by OlaHulleberg**
Please review that these changes work with your current method of making animations before accepting!

Linked issue: #7

How to test your animation with this solution:
Add your animation as a frameID in function ApplyFrame, and change the duration accordingly.

### CODE REVIEW

**Comment by OlaHulleberg** [comment]
Since we're using jQuery, you can add & remove classes with `$('.class-selector/#div-selector').addClass('class-name');` or `$('.class-selector/#div-selector').removeClass('class-name');`

**Comment by elizaveta-sergejevna** [comment]
Two things: 

1. I thought we agreed not to use jQuery because you're the only one in the group who knows how.

2. I don't understand what it means to add my animation as a frameID. Below is a simple keyframe-animation for a fade-in-effect applied to the first half of the first verse: 

`@keyframes fade-in-effect {`
    `0% {opacity: 0.0;}`
   ` 20% {opacity: 0.25;}`
   ` 40% {opacity: 0.45;}`
    `60% {opacity: 0.65;}`
    `80% {opacity: 0.85;}`
    `100% {opacity: 1.0;}`
`}`

`.first-half-verse1 {`
`animation-name: fade-in-effect;`
`animation-duration: 3s;`
`animation-iteration-count: 1;`
`animation-timing-function: linear;`
`animation-fill-mode: forwards;`
`}`

What do I do with this? Is this way of animating "compatible" with the js-code?

**Comment by OlaHulleberg** [comment]
1) You might have misunderstood me. Having jQuery in a project does NOT mean you HAVE to use jQuery, it's rather a QoL (Quality of life) addition. You can still do it the old clunky way if if you prefer. :)
jQuery is merely a library that gives you ADDITIONAL functionality. (and I sort of need that library for my clonky scrolling function :s)
jQuery is kind of like a .js file with lots of functions.

2) frameID is simply just the number correlated to the order of frame animations, meaning frameID 1 = first frame (starting frame), frameID 2 = second frame (first animation) and so on. As for now, frameID has no other function than merely being a number that increases when you scroll, and you can add your animation to.

`.first-half-verse1` is perfectly compatible with the code, you just add the class to the verse using javascript on say frameID 2.
image

**Comment by OlaHulleberg** [comment]
Oh, and remember to change your frameDuration to 3000, so it corresponds with your animation-duration of 3s! :)

**Comment by OlaHulleberg** [comment]
I'm merging this branch into master as I feel that the ground work has been done on the scrolling, but I will continue working on the mobile events for it. (Meaning the feature only works with a scroll wheel for now)

**Comment by elizaveta-sergejevna** [comment]
I'm sure you have done some great work! I would've loved to test it out, but I don't have any scroll wheels available at the moment :stuck_out_tongue:

**Pull request merged**
