### PR TITLE
Page design

### PR DESCRIPTION
**Pull request by elizaveta-sergejevna**
I made some minor changes in this branch which don't seem to have been implemented into the master branch. The changes mainly concern the positioning and styling of the text in addition to a minimal change in positioning of the tree-container. 

Please review and report back whether you agree or disagree with the changes! :clown_face:

### CODE REVIEW

**Comment by OlaHulleberg** [comment]
I'm not really sure about the color of the text
image

**Comment by elizaveta-sergejevna** [comment]
Yeah, I wasn't really sure about it either to be honest :sweat_smile: I initially thought it would be good to kind of go with the color palette established by the green tree and grass. But maybe the white text works better?

**Review by OlaHulleberg — CHANGES_REQUESTED** [review]
Text color should be changed, and maybe having a media query for 16/9 displays (f.i 1920x1080) where the text is at "flex-end" instead of "center" would be appropriate.

**Comment by elizaveta-sergejevna** [comment]
I'm sorry, I've completely forgotten about this. I agree that the green text color should be rejected, so I guess you could just deny my pull request :zany_face: (My other commits weren't that significant). Regarding the media query; isn't 16/9 the most common aspect ratio for desktops and for which we already are designing the project?

**Comment by OlaHulleberg** [comment]
@elizaveta-sergejevna My picture is of the website shown in a 16/9 aspect ratio.

**Comment by OlaHulleberg** [comment]
Are there any elements you want to keep from this pull?

**Comment by elizaveta-sergejevna** [comment]
Nah, if you're happy, I'm happy. Our time for nitpicking is starting to run out. Just close this badboy.

**Pull request closed without merging**
